CREATE TABLE "group" (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                         faculty VARCHAR(255),
                         number VARCHAR(255),
                         PRIMARY KEY (id)
);

CREATE TABLE student (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                         name VARCHAR(255),
                         last_name VARCHAR(255),
                         patronymic VARCHAR(255),
                         birth_date DATE,
                         group_id BIGINT,
                         PRIMARY KEY (id),
                         FOREIGN KEY (group_id) REFERENCES "group"(id)
);