vaadin:
  launch-browser: true
spring:
  application:
    name: Haulmont
  datasource:
    url: jdbc:hsqldb:file:./database/db;
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

    username: SA
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8021
